[parity]
chain = "/tmp/leo/parity-ethereum/build/classic.json"
base_path = "/tmp/leo/io.parity.ethereum2"

[mining]
force_sealing = true
reseal_on_txs = "all"
author = "0xdeadbeefcafe0000000000000000000000000001"
reseal_min_period = 4000
tx_queue_size = 2048

[rpc]
disable = false
port = 8541
interface = "all"
apis = ["all"]
hosts = ["all"]
cors = ["http://remix.ethereum.org"]

[websockets]
port = 8551

[ipfs]
enable = false # this is the default
hosts = ["all"]

[network]
port = 30301
