[parity]
no_consensus = true
chain = "/Users/leo/tests/ethereum_configs/mining.json"


[mining]
reseal_min_period = 0
min_gas_price = 0
author = "0xdeadbeefcafe0000000000000000000000000001"

[rpc]
interface = "all"
apis = ["all"]
hosts = ["all"]

[ipc]
apis = ["all"]


[ipfs]
enable = false # this is the default
hosts = ["all"]


#[misc]
#logging = "debug"
